'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''

step_val=0
fib_seq_val=1
sum=0
while(fib_seq_val<=4000000):
   if(fib_seq_val % 2==0):
      sum+=fib_seq_val
   step_val, fib_seq_val = fib_seq_val, fib_seq_val+step_val


print(sum)